### ISSUE TITLE
Make this available via Composer-Client

### ISSUE THREAD

**Issue by dtomasi** [ContaoBlackforest/form_multiupload_html5#1]
@baumannsven Could you pleas make this available via composer?

**Comment by baumannsven** [comment]
What about the dependencies?

**Comment by dtomasi** [comment]
This doesn´t have any? I will check it if you built the file-structure, OK?

**Comment by baumannsven** [comment]
Why isn't this conform with contaoblackforest, I built it.

**Comment by dtomasi** [comment]
Because its old, but never added to core of contao! I moved this from my own namespace to contaoblackforest a couple of weeks ago!

**Comment by baumannsven** [comment]
the package is now available for composer
